### ISSUE TITLE
Cannot run using docker-compose

### ISSUE THREAD

**Issue by loranger** [Kukkee/Kukkee#195]
Hello,

I try to make Kukkee work using docker-compose, behind traefik reverse proxy, but struggle to succeed

Here is my setup: 

```
├── .dockerignore
├── .env
├── Dockerfile
├── docker-compose.yml
├── mongodb_data_container
└── source
```

I did clone the repository as the `source` folder

<details>
<summary>.env</summary>

```ini
APP_PROJECT=kukkee
APP_DOMAIN=kukkee.docker # bound to 127.0.0.1

MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=rootpassword

NEXT_MONGODB_URI="mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${APP_PROJECT}-mongodb:27017"

NEXT_PUBLIC_BASE_URL="http://${APP_DOMAIN}"

NEXT_PUBLIC_BRAND_NAME="Kukkee"

NEXTAUTH_URL="http://${APP_DOMAIN}"

NEXTAUTH_SECRET=SUPERSECRET
```

</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.7'

services:
  mongo:
    container_name: ${APP_PROJECT}-mongodb
    image: mongo:4.4.6
    env_file:
      - .env
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db

  kukkee:
    container_name: ${APP_PROJECT}-kukkee
    image: ${APP_PROJECT}-kukkee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # ports:
    #   - 3000:3000
    labels:
      # Simple HTTP traefik support
      - "traefik.http.routers.${APP_PROJECT}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_PROJECT}-service.loadbalancer.server.port=3000"

networks:
  default:
      name: web # (shared with traefik)
```

</details>

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM node:16-alpine

# EXPOSE 3000

WORKDIR /app
COPY source/package.json source/package-lock.json /app/
RUN npm install

# node_modules folder is skipped from .dockerignore
COPY source /app/
RUN npm run build

CMD npm run start
```

</details>

When I try to reach kukkee.docker, I get an Internal Server Error

<img width="636" alt="Capture d’écran 2022-05-16 à 14 21 42" src="https://user-images.githubusercontent.com/6014/168591364-2deac721-7c44-49ac-95d9-0ed80a4ef56b.png">

<details>
<summary>here is my docker-compose log</summary>

```
docker-compose up
[+] Running 2/0
 ⠿ Container kukkee-kukkee   Recreated                                     0.1s
 ⠿ Container kukkee-mongodb  Recreated                                     0.1s
Attaching to kukkee-kukkee, kukkee-mongodb
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.263+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.264+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.264+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.266+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"6728fcd2b570"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.266+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.6","gitVersion":"72e66213c2c3eab37d9358d5e78ad7f5c1d0d0d7","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"aarch64","target_arch":"aarch64"}}}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.266+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.266+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"security":{"authorization":"enabled"}}}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.267+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.268+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=1447M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.282+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1652685563:282547][1:0xffff9b8cb450], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.287+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1652685563:287721][1:0xffff9b8cb450], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.292+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1652685563:292790][1:0xffff9b8cb450], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.293+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.293+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.293+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":948}}
kukkee-mongodb  | {"t":{"$date":"2022-05-16T07:19:23.293+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
kukkee-mongodb exited with code 14
kukkee-kukkee   |
kukkee-kukkee   | > kukkee@1.0.0 start
kukkee-kukkee   | > next start
kukkee-kukkee   |
kukkee-kukkee   | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
kukkee-kukkee   | [next-auth][error][CLIENT_FETCH_ERROR]
kukkee-kukkee   | https://next-auth.js.org/errors#client_fetch_error request to http://kukkee.docker/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
kukkee-kukkee   |   error: {
kukkee-kukkee   |     message: 'request to http://kukkee.docker/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:80',
kukkee-kukkee   |     stack: 'FetchError: request to http://kukkee.docker/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
kukkee-kukkee   |       '    at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:64142)\n' +
kukkee-kukkee   |       '    at ClientRequest.emit (node:events:527:28)\n' +
kukkee-kukkee   |       '    at Socket.socketErrorListener (node:_http_client:454:9)\n' +
kukkee-kukkee   |       '    at Socket.emit (node:events:527:28)\n' +
kukkee-kukkee   |       '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
kukkee-kukkee   |       '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
kukkee-kukkee   |       '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
kukkee-kukkee   |     name: 'FetchError'
kukkee-kukkee   |   },
kukkee-kukkee   |   path: 'session',
kukkee-kukkee   |   header: {
kukkee-kukkee   |     host: 'kukkee.docker',
kukkee-kukkee   |     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0',
kukkee-kukkee   |     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
kukkee-kukkee   |     'accept-encoding': 'gzip, deflate',
kukkee-kukkee   |     'accept-language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
kukkee-kukkee   |     'cache-control': 'no-cache',
kukkee-kukkee   |     cookie: 'next-auth.csrf-token=dcb2e1853809bc13ccd9ad044089f93fb7975ba4db10ec01d163f9329ca428a3%7C8d55e711f93471073d0d244bbb997fd1f84f4ebe2cec77f4e75facc5fee72711; next-auth.callback-url=http%3A%2F%2Fkukkee.docker',
kukkee-kukkee   |     dnt: '1',
kukkee-kukkee   |     pragma: 'no-cache',
kukkee-kukkee   |     'upgrade-insecure-requests': '1',
kukkee-kukkee   |     'x-forwarded-for': '172.18.0.1',
kukkee-kukkee   |     'x-forwarded-host': 'kukkee.docker',
kukkee-kukkee   |     'x-forwarded-port': '80',
kukkee-kukkee   |     'x-forwarded-proto': 'http',
kukkee-kukkee   |     'x-forwarded-server': 'a3ee11e90459',
kukkee-kukkee   |     'x-real-ip': '172.18.0.1'
kukkee-kukkee   |   },
kukkee-kukkee   |   message: 'request to http://kukkee.docker/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:80'
kukkee-kukkee   | }
kukkee-kukkee   | FetchError: request to http://kukkee.docker/api/admin/poll/getAll failed, reason: connect ECONNREFUSED 127.0.0.1:80
kukkee-kukkee   |     at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:64142)
kukkee-kukkee   |     at ClientRequest.emit (node:events:527:28)
kukkee-kukkee   |     at Socket.socketErrorListener (node:_http_client:454:9)
kukkee-kukkee   |     at Socket.emit (node:events:527:28)
kukkee-kukkee   |     at emitErrorNT (node:internal/streams/destroy:157:8)
kukkee-kukkee   |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
kukkee-kukkee   |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
kukkee-kukkee   |   type: 'system',
kukkee-kukkee   |   errno: 'ECONNREFUSED',
kukkee-kukkee   |   code: 'ECONNREFUSED'
kukkee-kukkee   | }
```

</details>

It seems I missed an important step, but I cannot figure out which one.
Can you help, please ?

**Environment**
 - OS: Docker 20.10.14 build a224086 under macOS 12.3.1
 - Docker compose 2.5.0
 - Browser Firefox 102

**Comment by AnandBaburajan** [comment]
Hello @loranger. Maybe https://stackoverflow.com/a/61147916/6320130 or https://stackoverflow.com/a/71260383/6320130 or something related might help. We'll have an official Docker image soon. Also, just FYI, we're planning to substantially change the project due to some change of plans because of unforseen circumstances.

**Comment by loranger** [comment]
Thanks for your support, but I think I'll wait for an official docker image, it sounds wiser ;)

Thanks again
